name: Maintenance
on:
  schedule:
    - cron: "0 3 * * *"  # Run daily at 3:00 AM UTC
  workflow_dispatch:

permissions: {}

jobs:
  purge-cache:
    name: Purge Cache
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      actions: write
    steps:
      - uses: MyAlbum/purge-cache@881eb5957687193fa612bf74c0042adc78ea5e54 # v2.2.0
        with:
          accessed: true
          created: false
          max-age: 259200 # 3 days in seconds
          debug: true
